### ISSUE TITLE
applying jsfit to multilateration like problems

### ISSUE THREAD

**Issue by MattMacGillivray** [reptillicus/jsfit#1]
Playing around with your library, wondering if you had used it to solve trilateration/multilateration type problems?  For example, solving 3 or more circle equations ( r<sub>1</sub><sup>2</sup> = (x-x<sub>1</sub>)<sup>2</sup> - (y-y<sub>1</sub>)<sup>2</sup> ) for the users position (x,y)?

Our known data set would be r<sub>1</sub>, x<sub>1</sub>, y<sub>1</sub>, solving for the best (x,y).

Can't figure out if that will work in the code as it is now?

Thanks,

Matt.

**Comment by reptillicus** [comment]
Hey Matt, 

Yeah it should work from what you have written above. You can overload the residuals method on the fitter, its set by default to work for most common problems, but can overload it for cases like this. If I have time today I can put something together and send it to you.

**Comment by MattMacGillivray** [comment]
That would be awesome.  I spent a few hours trying to make it work in jsfit, but wasn't having much luck.

Thanks so much!

Matt.

**Comment by MattMacGillivray** [comment]
Any luck?

**Comment by wuj3888** [comment]
Hi Joe - I wanted to follow up and see if there was any chance you could help us out on this. We’re really need to get this working in JS by the weekend, and we’ve pretty much exhausted all other avenues we can think of. You’re our best hope at the moment! If you have a few minutes to help us understand how to use jsfit for this problem - how to define the function, how the parameters need to be set - it would be most appreciated. Thanks!

James

**Comment by reptillicus** [comment]
Working up an example now, should be done by end of day. For now, I think you can just use a model like this: 
function model (x, params) {
    r = Math.sqrt( Math.pow((x[0] - params[0]), 2) + 
                   Math.pow((x[1] - params[1]), 2) + 
                   Math.pow((x[2] - params[2]), 2)
                  );
    return r; 
  }

And pass the data in a 2-d array:
 xvals = [
            [1, 0, 0],
            [0, 2, 0], 
            [0, 0, 3], 
            [0, 3, 4],
            [0, 3, 4], 
          ];
 yvals = [1, 2, 3, 5, 5.5];

Here, yvals is the r1 from your example above. 

data = [xvals, yvals];
par0 = [0.5, 0.5, 0.5];
fitobj  = jsfit.fit(model, data, par0, {'debug': true });

**Comment by MattMacGillivray** [comment]
So, through your example, if I wanted to apply jsfit to trilateration (or multilateration) as noted in my original question, I've got..

r<sub>1</sub> = (x<sub>0</sub> - x<sub>1</sub>)<sup>2</sup> - (y<sub>0</sub> - y<sub>1</sub>)<sup>2</sup>
r<sub>2</sub> = (x<sub>0</sub> - x<sub>2</sub>)<sup>2</sup> - (y<sub>0</sub> - y<sub>2</sub>)<sup>2</sup>
r<sub>3</sub> = (x<sub>0</sub> - x<sub>3</sub>)<sup>2</sup> - (y<sub>0</sub> - y<sub>3</sub>)<sup>2</sup>

where we know ( r<sub>i</sub>, x<sub>i</sub>, y<sub>i</sub> ), and are solving for ( x<sub>0</sub>, y<sub>0</sub> ).

Which translates to:

function model (x, par0) {
  r = Math.sqrt( Math.pow((x[0] - par0[0]), 2) - Math.pow((x[1] - par0[1]), 2) );
  return r; 
}

xvals = [
[ x<sub>1</sub>, y<sub>1</sub> ],
[ x<sub>2</sub>, y<sub>2</sub> ],
[ x<sub>3</sub>, y<sub>3</sub> ],
];
yvals = [ r<sub>1</sub>, r<sub>2</sub>, r<sub>3</sub> ];

data = [xvals, yvals]
par0 = [ x<sub>0</sub>, y<sub>0</sub> ];  // where these are our best initial guesses
fitobj = jsfit(model, data, par0, {'debug': true});

and the fitobj will contain the best  x<sub>0</sub> (par0[0]), y<sub>0</sub> (par0[1]) that it found?

Matt.

**Comment by wuj3888** [comment]
Thanks for getting back to us Joe! I tried Matt's interpretation above, but numeric.js isn't having it. If you could help us understand how to use the xvals matrix so that it represents [xi, yi] with the three columns it would be really helpful :) Thanks again!

**Comment by reptillicus** [comment]
If you have exactly 3 points, you are probably getting an error because the hessian becomes singular (basically a perfect fit, so there are perfectly defined parameters and no degrees of freedom). I'm about to push a temporary fix for this scenario for now. However, if that is your real use case, you don't need to do least squares, can use straight forward linear algebra to determine the solution to the equations.

**Comment by wuj3888** [comment]
Thanks, Joe.  I tried it with more than 3 points, and it still fails. I think I just need some clarity on how the parameters we have are used correctly. I don't understand how to represent the x and y coordinates of the points in the xvals matrix as you've shown.

We've been able to solve the exactly 3 point scenario using linear algebra. But the least squares approach allows us to solve the problem for >3 points, which gives us much better accuracy. So, while Matt's example considers xvals = [[x1,y1],[x2,y2],[x3,y3]] and yvals = [r1,r2,r3], the real problem we want to solve is ,[[x1,y1],....,[xn,yn]] and [r1,...,rn].

Your help is greatly appreciated!

**Comment by reptillicus** [comment]
Ok, one sec and I'll push some changes up to github pages

**Comment by reptillicus** [comment]
Pushed up some changes, please let me know if its working. The issue was probably related to the use of Float32 arrays for the data. Need better way of handling converting the data into the typed arrays.

**Comment by wuj3888** [comment]
Thanks, Joe. I'll try it now and let you know. We really appreciate the help you've provided!

**Comment by wuj3888** [comment]
Hi Joe - it seems to be working better now. It works as expected in the Eclipse browser, but breaks in Chrome/Safari with the same error as before though. Could the fix be browser sensitive?

**Comment by reptillicus** [comment]
It is working for me in Chrome, can you post the error stack?

**Comment by reptillicus** [comment]
There is a demo at http://josephmeiring.github.io/jsfit/#/examples/5 

The source for that little example is in the code

**Comment by wuj3888** [comment]
![image](https://cloud.githubusercontent.com/assets/11082782/7211141/e969efda-e525-11e4-8122-5d26a66a644e.png)

**Comment by reptillicus** [comment]
Any way you could share the data that made it error out?

**Comment by wuj3888** [comment]
yvals = 
[515.9089066879927 ,
272.7673000929547,
474.09070862019644,
350.202798389733,
440.9104217411968,
262.60616900598507,
51.40038910358559,
152.190669884852]

xvals: = [ [10, 10],
[480, 10],
[10, 460],
[240, 0],
[10, 240],
[240, 440],
[480, 240],
[480,430]]

**Comment by wuj3888** [comment]
Hi Joe - It's actually throwing errors in the Eclipse browser too. Not sure why it was working at first there. One of the mysteries of coding... :P 

As always your help with this very appreciated!

**Comment by reptillicus** [comment]
Could be starting values? How are you determining starting parameters?

**Comment by reptillicus** [comment]
Also, should not use 0.0 as a starting param.

**Comment by reptillicus** [comment]
Can take a deeper look later this evening

**Comment by wuj3888** [comment]
Do you mean for p0? It's [0.5, 0.5, 0.5]...

Thanks, Joe.

**Comment by wuj3888** [comment]
I got it working, Joe. It was the initial starting parameters. Thanks so much for your help with this!

**Comment by reptillicus** [comment]
OK great. Just doing some testing, I got it to not error out even with starting params of [0.5, 0.5]

I would suggest using the mean values of the X data as starting vals.

**Comment by reptillicus** [comment]
Put an example up on the docs site, can open console and see what its doing in debug mode. Starting params are important for all these iterative fitters. With bad starting params, can end up in a non-global minimum. Need to update docs to mention these things. Anyway, thanks for helping find some bugs! Let me know if any more come up. Note, this is still a project much in progress. The underlying API of the fitter probably won't change much, but other things will.

**Comment by wuj3888** [comment]
I'm now using the mean values as the starting point, and it's working as expected again. This is an amazing project, and as far as I can tell the only one for JS of its kind. You've been incredibly helpful and generous with your time Joe. Thanks again!
