### ISSUE TITLE
Checking if

### ISSUE THREAD

**Issue by nowherenearithaca** [reptillicus/jsfit#2]
I don't know if you're messing with this much anymore, but was curious why you are checking if the sum of the entries of the Hessian is zero before calculating the inverse rather than checking if the determinant is zero - this it at https://github.com/josephmeiring/jsfit/blob/master/src/jsfit.js#L157

Wonder if I'm missing something here !

**Comment by reptillicus** [comment]
Yes, still kind of working on it. Any contributions welcome. I can't remember at the moment as to why that check is in there, would have to look at that part again. Seems like Det(H) should work?

**Comment by nowherenearithaca** [comment]
yes det(H) should work if you want to do something else when the matrix is not invertible. I didn't look into what you're doing when it is singular. I changed the check and it seemed to help.  I've also tweaked a little on the "limits" stuff but it still can go outside the bounds when it looks for the next set of parameters to use.  Nonlinear curve fitting is so touchy, imo.

**Comment by reptillicus** [comment]
Cool, if you have the limiting stuff ready I can merge it in. Non-Linear curve fitting is indeed pretty touchy. There are still a few edge cases that fail with JSfit, need to get back to working on it when I have some more time. Again, any help appreciated!
